In [1]:
import numpy  as np


In [3]:
A= np.array(
    [[2., - 1.,  1.,  1.],
     [1.,  2., - 1., - 1.],
        [-1.,  2.,  2.,  2.],
        [1., - 1.,  2.,  1.]]
)
A

array([[ 2., -1.,  1.,  1.],
       [ 1.,  2., -1., -1.],
       [-1.,  2.,  2.,  2.],
       [ 1., -1.,  2.,  1.]])

In [11]:
A.shape

(4, 4)

In [6]:
b= np.array([ 6.,  3., 14.,  8.])
b.shape

(4,)

In [15]:
b= b.reshape((4,1))
b.shape

(4, 1)

In [16]:
b

array([[ 6.],
       [ 3.],
       [14.],
       [ 8.]])

In [17]:
A= np.hstack((A,b))
A

array([[ 2., -1.,  1.,  1.,  6.],
       [ 1.,  2., -1., -1.,  3.],
       [-1.,  2.,  2.,  2., 14.],
       [ 1., -1.,  2.,  1.,  8.]])